package com.halil.chatapp.other

object MyDataObject {

    val dortYillikBolumler = listOf(
        "Arkeoloji ve Sanat Tarihi",
        "Basın ve Yayın",
        "Coğrafya",
        "Coğrafya Öğretmenliği",
        "Çağdaş Türk Lehçeleri ve Edebiyatları",
        "Çerkez Dili ve Edebiyatı",
        "Çizgi Film ve Animasyon",
        "El Sanatları",
        "Film Tasarımı ve Yazarlığı",
        "Film Tasarımı ve Yönetimi",
        "Film Tasarım ve Yönetmenliği",
        "Fotoğraf",
        "Fotoğraf ve Video",
        "Gastronomi ve Mutfak Sanatları",
        "Gazetecilik",
        "Geleneksel Türk Sanatları",
        "Görsel İletişim Tasarımı",
        "Görsel Sanatlar",
        "Görsel Sanatlar ve İletişim",
        "Gürcü Dili ve Edebiyatı",
        "Halkla İlişkiler",
        "Halkla İlişkiler ve Reklamcılık",
        "Halkla İlişkiler ve Tanıtım",
        "İlahiyat",
        "İletişim Bilimleri",
        "İletişim Fakültesi",
        "İletişim Sanatları",
        "İletişim Tasarımı ve Yönetimi",
        "İletişim ve Tasarım",
        "İslam Bilimleri",
        "İslami İlimler",
        "Kazak Dili ve Edebiyatı",
        "Kurgu, Ses ve Görüntü Yönetimi",
        "Kültür ve İletişim Bilimleri",
        "Kürt Dili ve Edebiyatı",
        "Medya ve Görsel Sanatlar",
        "Medya ve İletişim",
        "Okul Öncesi Öğretmenliği",
        "Özel Eğitim Öğretmenliği",
        "Radyo, Televizyon ve Sinema",
        "Reklam Tasarımı ve İletişimi",
        "Reklamcılık",
        "Rekreasyon Yönetimi",
        "Sanat Tarihi",
        "Sanat ve Kültür Yönetimi",
        "Sinema ve Dijital Medya",
        "Sinema ve Televizyon",
        "Sosyal Bilgiler Öğretmenliği",
        "Süryani Dili ve Edebiyatı",
        "Tarih",
        "Tarih Öğretmenliği",
        "Televizyon Haberciliği ve Programcılığı",
        "Tiyatro Eleştirmenliği ve Dramaturji",
        "Türk Dili ve Edebiyatı",
        "Türk Dili ve Edebiyatı Öğretmenliği",
        "Türkçe Öğretmenliği",
        "Yeni Medya",
        "Yeni Medya ve İletişim",
    )
    val ikiYilliBolumler = listOf(
        "Adalet",
        "Aşçılık",
        "Büro Yönetimi ve Yönetici Asistanlığı",
        "Çocuk Gelişimi",
        "Fotoğrafçılık ve Kameramanlık",
        "Geleneksel El Sanatları",
        "Halıcılık ve Kilimcilik",
        "Halkla İlişkiler ve Tanıtım",
        "Hukuk Büro Yönetimi ve Sekreterliği",
        "İlahiyat",
        "Kültürel Miras ve Turizm",
        "Marka İletişimi",
        "Medya ve İletişim",
        "Mimari Dekoratif Sanatlar",
        "Radyo ve Televizyon Programcılığı",
        "Reklamcılık",
        "Saç Bakımı ve Güzellik Hizmetleri",
        "Tıbbi Dokümantasyon ve Sekreterlik",
        "Turist Rehberliği (2 Yıllık)",
        "Turizm Animasyonu (2 Yıllık)",
        "Uygulamalı İngilizce Çevirmenlik (2 Yıllık)",
        "Uygulamalı İspanyolca Çevirmenlik (2 Yıllık)",
        "Uygulamalı Rusça ve Çevirmenlik",
        "Yerel Yönetimler",
    )

    val sayisaldortYillikBolumler = listOf(
        "Acil Yardım ve Afet Yönetimi",
        "Adli Bilimler",
        "Adli Bilişim Mühendisliği",
        "Ağaç İşleri Endüstri Mühendisliği",
        "Aktüerya Bilimleri",
        "Astronomi ve Uzay Bilimleri",
        "Bahçe Bitkileri",
        "Balıkçılık Teknolojisi Mühendisliği",
        "Basım Teknolojileri",
        "Beslenme ve Diyetetik",
        "Bilgi Güvenliği Teknolojisi",
        "Bilgisayar Bilimleri",
        "Bilgisayar Mühendisliği",
        "Bilgisayar Teknolojisi ve Bilişim Sistemleri",
        "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği",
        "Bilişim Sistemleri Mühendisliği",
        "Bilişim Sistemleri ve Teknolojileri",
        "Bitki Koruma",
        "Bitkisel Üretim ve Teknolojileri",
        "Biyoenformatik ve Genetik",
        "Biyokimya",
        "Biyoloji",
        "Biyoloji Öğretmenliği",
        "Biyomedikal Mühendisliği",
        "Biyomühendislik",
        "Biyosistem Mühendisliği",
        "Biyoteknoloji",
        "Cevher Hazırlama Mühendisliği",
        "Çevre Mühendisliği",
        "Deniz Bilimleri ve Teknolojisi Mühendisliği",
        "Deniz Ulaştırma İşletme Mühendisliği",
        "Deri Mühendisliği",
        "Dijital Oyun Tasarımı",
        "Dil ve Konuşma Terapisi",
        "Diş Hekimliği (5 Yıllık)",
        "Ebelik",
        "Eczacılık (5 Yıllık)",
        "Elektrik Mühendisliği",
        "Elektrik-Elektronik Mühendisliği",
        "Elektronik Mühendisliği",
        "Elektronik ve Haberleşme Mühendisliği",
        "Endüstri Mühendisliği",
        "Endüstriyel Tasarım",
        "Endüstriyel Tasarım Mühendisliği",
        "Enerji Mühendisliği",
        "Enerji Sistemleri Mühendisliği",
        "Ergoterapi",
        "Fen Bilgisi Öğretmenliği",
        "Fizik",
        "Fizik Mühendisliği",
        "Fizik Öğretmenliği",
        "Fizyoterapi ve Rehabilitasyon",
        "Fotonik",
        "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
        "Gemi Makineleri İşletme Mühendisliği",
        "Gemi ve Deniz Teknolojisi Mühendisliği",
        "Gemi ve Yat Tasarımı",
        "Genetik ve Biyomühendislik",
        "Genetik ve Yaşam Bilimleri Programları",
        "Geomatik Mühendisliği",
        "Gıda Mühendisliği",
        "Gıda Teknolojisi",
        "Harita Mühendisliği Taban Puanları",
        "Havacılık Elektrik ve Elektroniği",
        "Havacılık ve Uzay Mühendisliği",
        "Hayvansal Üretim ve Teknolojileri",
        "Hemşirelik",
        "Hidrojeoloji Mühendisliği",
        "İç Mimarlık",
        "İlköğretim Matematik Öğretmenliği",
        "İmalat Mühendisliği",
        "İnşaat Mühendisliği",
        "İstatistik",
        "İstatistik ve Bilgisayar Bilimleri",
        "İş Sağlığı ve Güvenliği",
        "İşletme Mühendisliği",
        "Jeofizik Mühendisliği",
        "Jeoloji Mühendisliği",
        "Kanatlı Hayvan Yetiştiriciliği",
        "Kentsel Tasarım ve Peyzaj Mimarlığı",
        "Kimya",
        "Kimya Mühendisliği",
        "Kimya Öğretmenliği",
        "Kimya-Biyoloji Mühendisliği",
        "Kontrol ve Otomasyon Mühendisliği",
        "Maden Mühendisliği",
        "Makine Mühendisliği",
        "Malzeme Bilimi ve Mühendisliği",
        "Malzeme Bilimi ve Nanoteknoloji Mühendisliği",
        "Malzeme Bilimi ve Teknolojileri",
        "Matematik",
        "Matematik Mühendisliği",
        "Matematik Öğretmenliği",
        "Matematik ve Bilgisayar Bilimleri",
        "Mekatronik Mühendisliği",
        "Metalurji ve Malzeme Mühendisliği",
        "Meteoroloji Mühendisliği",
        "Mimarlık",
        "Moleküler Biyoloji ve Genetik",
        "Moleküler Biyoteknoloji",
        "Mühendislik Programları",
        "Mühendislik ve Doğa Bilimleri Programları",
        "Nanobilim ve Nanoteknoloji",
        "Nanoteknoloji Mühendisliği",
        "Nükleer Enerji Mühendisliği",
        "Odyoloji",
        "Optik ve Akustik Mühendisliği",
        "Orman Endüstrisi Mühendisliği",
        "Orman Mühendisliği",
        "Otomotiv Mühendisliği",
        "Perfüzyon",
        "Petrol ve Doğalgaz Mühendisliği",
        "Peyzaj Mimarlığı",
        "Pilotaj",
        "Raylı Sistemler Mühendisliği",
        "Su Bilimleri ve Mühendisliği",
        "Su Ürünleri Mühendisliği",
        "Süt Teknolojisi",
        "Şehir ve Bölge Planlama",
        "Tarım Makineleri ve Teknolojileri Mühendisliği",
        "Tarımsal Biyoteknoloji",
        "Tarımsal Genetik Mühendisliği",
        "Tarımsal Yapılar ve Sulama",
        "Tarla Bitkileri",
        "Tekstil Mühendisliği",
        "Tıp (6 Yıllık)",
        "Tıp Mühendisliği",
        "Tohum Bilimi ve Teknolojisi",
    )
    val sayisalikiYilliBolumler = listOf(
        "Acil Durum ve Afet Yönetimi",
        "Ağız ve Diş Sağlığı",
        "Alternatif Enerji Kaynakları Teknolojisi",
        "Ameliyathane Hizmetleri",
        "Anestezi",
        "Ayakkabı Tasarım ve Üretimi",
        "Beton Teknolojisi",
        "Bilgi Güvenliği Teknolojisi",
        "Bilgisayar Destekli Tasarım ve Animasyon",
        "Bilgisayar Operatörlüğü",
        "Bilgisayar Programcılığı",
        "Bilgisayar Teknolojisi",
        "Bitki Koruma",
        "Biyokimya",
        "Biyomedikal Cihaz Teknolojisi",
        "Boya Teknolojisi",
        "Coğrafi Bilgi Sistemleri",
        "Coğrafi Bilgi Sistemleri ve Teknolojileri",
        "Çevre Koruma ve Kontrol",
        "Çevre Sağlığı",
        "Deniz Ulaştırma ve İşletme",
        "Deri Teknolojisi",
        "Diş Protez Teknolojisi",
        "Diyaliz",
        "Doğalgaz ve Tesisatı Teknolojisi",
        "Döküm",
        "Eczane Hizmetleri",
        "Elektrik",
        "Elektrik Enerjisi Üretim, İletim ve Dağıtımı",
        "Elektrikli Cihaz Teknolojisi",
        "Elektromekanik Taşıyıcılar",
        "Elektronik Haberleşme Teknolojisi",
        "Elektronik Teknolojisi",
        "Elektronörofizyoloji",
        "Endüstri Ürünleri Tasarımı",
        "Endüstriyel Cam ve Seramik",
        "Endüstriyel Kalıpçılık",
        "Enerji Tesisleri İşletmeciliği",
        "Engelli Bakımı ve Rehabilitasyon",
        "Evde Hasta Bakımı",
        "Fizyoterapi",
        "Gaz ve Tesisatı Teknolojisi",
        "Gemi İnşaatı",
        "Gemi Makineleri İşletme",
        "Geoteknik",
        "Gıda Kalite Kontrolü ve Analizi",
        "Gıda Teknolojisi",
        "Giyim Üretim Teknolojisi",
        "Harita ve Kadastro",
        "İklimlendirme ve Soğutma Teknolojisi",
        "İlk ve Acil Yardım",
        "İnşaat Teknolojisi",
        "İnternet ve Ağ Teknolojileri",
        "İş Makineleri Operatörlüğü",
        "İş Sağlığı ve Güvenliği",
        "Kimya Teknolojisi",
        "Kontrol ve Otomasyon Teknolojisi",
        "Laborant ve Veteriner Sağlık",
        "Laboratuvar Teknolojisi",
        "Lastik ve Plastik Teknolojisi",
        "Maden Teknolojisi",
        "Makine",
        "Makine, Resim ve Konstrüksiyon",
        "Mekatronik",
        "Mobil Teknolojileri",
        "Mobilya ve Dekorasyon",
        "Nükleer Teknoloji ve Radyasyon Güvenliği",
        "Nükleer Tıp Teknikleri",
        "Odyometri",
        "Optisyenlik",
        "Ortopedik Protez ve Ortez",
        "Oto Boya ve Karoseri",
        "Otomotiv Teknolojisi",
        "Otopsi Yardımcılığı",
        "Patoloji Laboratuvar Teknikleri",
        "Perfüzyon Teknikleri",
        "Podoloji",
        "Radyo ve Televizyon Teknolojisi",
        "Radyoterapi",
        "Rafineri ve Petro-Kimya Teknolojisi",
        "Raylı Sistemler Elektrik ve Elektronik Teknolojisi",
        "Raylı Sistemler Makine Teknolojisi",
        "Raylı Sistemler Makinistlik",
        "Raylı Sistemler Yol Teknolojisi",
        "Sağlık Bilgi Sistemleri Teknikerliği",
        "Sahne ve Gösteri Sanatları Teknolojisi",
        "Seramik, Cam ve Çinicilik",
        "Tarım Makineleri",
        "Tekstil Teknolojisi",
        "Tekstil ve Halı Makineleri",
        "Tıbbi Görüntüleme Teknikleri",
        "Tıbbi Laboratuvar Teknikleri",
        "Uçak Teknolojisi",
        "Üretimde Kalite Kontrol",
        "Web Tasarımı ve Kodlama",
        "Yapı Denetimi",
        "Yapı Ressamlığı",
        "Yapı Tesisat Teknolojisi",
        "Yapı Yalıtım Teknolojisi"
    )

    val esitdortYillikBolumler = listOf(
        "Aile ve Tüketici Bilimleri",
        "Antrenörlük Eğitimi",
        "Antropoloji",
        "Arkeoloji",
        "Ayakkabı Tasarımı ve Üretimi",
        "Bankacılık",
        "Bankacılık ve Finans",
        "Bankacılık ve Sigortacılık",
        "Beden Eğitimi ve Spor Öğretmenliği",
        "Bilgi ve Belge Yönetimi",
        "Bilim Tarihi",
        "Çalışma Ekonomisi ve Endüstri İlişkileri",
        "Çocuk Gelişimi",
        "Denizcilik İşletmeleri Yönetimi",
        "Egzersiz ve Spor Bilimleri",
        "Ekonometri",
        "Ekonomi",
        "Ekonomi ve Finans",
        "Enerji Yönetimi",
        "Felsefe",
        "Felsefe Grubu Öğretmenliği",
        "Gayrimenkul Geliştirme ve Yönetimi",
        "Girişimcilik",
        "Grafik",
        "Grafik Tasarımı",
        "Gümrük İşletme",
        "Havacılık Yönetimi",
        "Hukuk",
        "İç Mimarlık ve Çevre Tasarımı",
        "İktisadi ve İdari Bilimler Programları",
        "İktisadi ve İdari Programlar",
        "İktisat",
        "İnsan Kaynakları Yönetimi",
        "İslam İktisadı ve Finans",
        "İşletme",
        "Kamu Yönetimi",
        "Klasik Arkeoloji",
        "Kuyumculuk ve Mücevher Tasarımı",
        "Kültür Varlıklarını Koruma ve Onarım",
        "Küresel Siyaset ve Uluslararası İlişkiler",
        "Lojistik Yönetimi",
        "Maliye",
        "Moda Tasarımı",
        "Muhasebe ve Denetim",
        "Muhasebe ve Finans Yönetimi",
        "Müzecilik",
        "Organik Tarım İşletmeciliği",
        "Otel Yöneticiliği",
        "Pazarlama",
        "Politika ve Ekonomi",
        "Protohistorya ve Ön Asya Arkeolojisi",
        "Psikoloji",
        "Psikolojik Danışmanlık ve Rehberlik",
        "Psikolojik Danışmanlık ve Rehberlik Öğretmenliği",
        "Rehberlik ve Psikolojik Danışmanlık",
        "Rekreasyon",
        "Sağlık Yönetimi",
        "Sanat ve Sosyal Bilimler Programları",
        "Sermaye Piyasası",
        "Seyahat İşletmeciliği",
        "Seyahat İşletmeciliği ve Turizm Rehberliği",
        "Sınıf Öğretmenliği",
        "Sigortacılık",
        "Sigortacılık ve Aktüerya Bilimleri",
        "Sigortacılık ve Risk Yönetimi",
        "Sigortacılık ve Sosyal Güvenlik",
        "Siyasal Bilimler",
        "Siyaset Bilimi",
        "Siyaset Bilimi ve Kamu Yönetimi",
        "Siyaset Bilimi ve Uluslararası İlişkiler",
        "Sosyal Hizmet",
        "Sosyal ve Siyasal Bilimler",
        "Sosyoloji",
        "Spor Yöneticiliği",
        "Takı Tasarımı",
        "Tapu Kadastro",
        "Tarım Ekonomisi",
        "Tarım Ticareti ve İşletmeciliği",
        "Tarih Öncesi Arkeolojisi",
        "Teknoloji ve Bilgi Yönetimi",
        "Tekstil Tasarımı",
        "Tekstil ve Moda Tasarımı",
        "Turizm İşletmeciliği",
        "Turizm ve Otel İşletmeciliği",
        "Türk İslam Arkeolojisi",
        "Uluslararası Ekonomik İlişkiler",
        "Uluslararası Finans",
        "Uluslararası Finans ve Bankacılık",
        "Uluslararası Girişimcilik",
        "Uluslararası İlişkiler",
        "Uluslararası İşletme Yönetimi",
        "Uluslararası Ticaret",
        "Uluslararası Ticaret ve Finans",
        "Uluslararası Ticaret ve Finansman",
        "Uluslararası Ticaret ve İşletmecilik",
        "Uluslararası Ticaret ve Lojistik",
        "Uluslararası Ulaştırma Sistemleri",
        "Yiyecek ve İçecek İşletmeciliği",
        "Yönetim Bilimleri Programları",
        "Yönetim Bilişim Sistemleri"
    )
    val esitikiYilliBolumler = listOf(
        "Bankacılık ve Sigortacılık",
        "Basım ve Yayın Teknolojileri",
        "Bilgi Yönetimi",
        "Çay Tarımı ve İşleme Teknolojisi",
        "Çevre Temizliği ve Denetimi",
        "Çim Alan Tesisi ve Yönetimi",
        "Çocuk Koruma ve Bakım Hizmetleri",
        "Deniz Brokerliği",
        "Deniz ve Liman İşletmeciliği",
        "Dış Ticaret",
        "Doğal Yapı Taşları Teknolojisi",
        "Emlak ve Emlak Yönetimi",
        "Endüstriyel Tavukçuluk",
        "Eser Koruma",
        "Et ve Ürünleri Teknolojisi",
        "Fındık Eksperliği",
        "Fidan Yetiştiriciliği",
        "Grafik Tasarımı",
        "Hava Lojistiği",
        "İç Mekan Tasarımı",
        "İkram Hizmetleri",
        "İnsan Kaynakları Yönetimi",
        "İşletme Yönetimi",
        "Kooperatifçilik",
        "Kuyumculuk ve Takı Tasarımı",
        "Kültür Balıkçılığı",
        "Lojistik",
        "Maliye",
        "Marina İşletme",
        "Marina ve Yat İşletmeciliği",
        "Menkul Kıymetler ve Sermaye Piyasası",
        "Meyve ve Sebze İşleme Teknolojisi",
        "Mimari Restorasyon",
        "Moda Yönetimi",
        "Moda Tasarımı",
        "Muhasebe ve Vergi Uygulamaları",
        "Organik Tarım",
        "Ormancılık ve Orman Ürünleri",
        "Otobüs Kaptanlığı",
        "Özel Güvenlik ve Koruma",
        "Pazarlama",
        "Perakende Satış ve Mağaza Yönetimi",
        "Peyzaj ve Süs Bitkileri",
        "Posta Hizmetleri",
        "Raylı Sistemler İşletmeciliği",
        "Sağlık Kurumları İşletmeciliği",
        "Sağlık Turizmi İşletmeciliği",
        "Sahne ve Dekor Tasarımı",
        "Seracılık",
        "Sivil Hava Ulaştırma İşletmeciliği",
        "Sivil Havacılık Kabin Hizmetleri",
        "Sivil Savunma ve İtfaiyecilik",
        "Sosyal Güvenlik",
        "Sosyal Hizmetler",
        "Spor Yönetimi",
        "Su Altı Teknolojisi",
        "Süs Bitkileri Yetiştiriciliği",
        "Süt ve Ürünleri Teknolojisi",
        "Tapu ve Kadastro",
        "Tarım",
        "Tarımsal İşletmecilik",
        "Tarımsal Ürünler Muhafaza ve Depolama Teknolojisi",
        "Tarla Bitkileri",
        "Tıbbi Tanıtım ve Pazarlama",
        "Tıbbi ve Aromatik Bitkiler",
        "Tohumculuk",
        "Turizm ve Otel İşletmeciliği",
        "Turizm ve Seyahat Hizmetleri",
        "Uçuş Harekat Yöneticiliği",
        "Ulaştırma ve Trafik Hizmetleri",
        "Yat İşletme ve Yönetimi",
        "Zeytincilik ve Zeytin İşleme Teknolojisi",
    )

    val dortYillikBolumlerEN = listOf(
        "Archaeology and Art History",
        "Press and Publishing",
        "Geography",
        "Geography Teaching",
        "Contemporary Turkish Dialects and Literatures",
        "Circassian Language and Literature",
        "Cartoon and Animation",
        "Handicrafts",
        "Film Design and Writing",
        "Film Design and Direction",
        "Film Design and Directing",
        "Photography",
        "Photography and Video",
        "Gastronomy and Culinary Arts",
        "Journalism",
        "Traditional Turkish Arts",
        "Visual Communication Design",
        "Visual Arts",
        "Visual Arts and Communication",
        "Georgian Language and Literature",
        "Public Relations",
        "Public Relations and Advertising",
        "Public Relations and Promotion",
        "Theology",
        "Communication Sciences",
        "Faculty of Communication",
        "Communication Arts",
        "Communication Design and Management",
        "Communication and Design",
        "Islamic Sciences",
        "Islamic Studies",
        "Kazakh Language and Literature",
        "Editing, Sound, and Image Management",
        "Culture and Communication Sciences",
        "Kurdish Language and Literature",
        "Media and Visual Arts",
        "Media and Communication",
        "Preschool Teaching",
        "Special Education Teaching",
        "Radio, Television, and Cinema",
        "Advertising Design and Communication",
        "Advertising",
        "Recreation Management",
        "Art History",
        "Art and Culture Management",
        "Cinema and Digital Media",
        "Cinema and Television",
        "Social Studies Teaching",
        "Syriac Language and Literature",
        "History",
        "History Teaching",
        "Television Journalism and Programming",
        "Theatre Criticism and Dramaturgy",
        "Turkish Language and Literature",
        "Turkish Language and Literature Teaching",
        "Turkish Teaching",
        "New Media",
        "New Media and Communication"
    )
    val ikiYilliBolumlerEN = listOf(
        "Justice",
        "Culinary Arts",
        "Office Management and Executive Assistance",
        "Child Development",
        "Photography and Cinematography",
        "Traditional Handicrafts",
        "Carpet and Kilim Weaving",
        "Public Relations and Promotion",
        "Legal Office Management and Secretarial Studies",
        "Theology",
        "Cultural Heritage and Tourism",
        "Brand Communication",
        "Media and Communication",
        "Architectural Decorative Arts",
        "Radio and Television Programming",
        "Advertising",
        "Hair Care and Beauty Services",
        "Medical Documentation and Secretarial Studies",
        "Tourist Guiding (2-Year Program)",
        "Tourism Animation (2-Year Program)",
        "Applied English Translation (2-Year Program)",
        "Applied Spanish Translation (2-Year Program)",
        "Applied Russian and Translation",
        "Local Governments"
    )

    val sayisaldortYillikBolumlerEN = listOf(
        "Emergency Aid and Disaster Management",
        "Forensic Sciences",
        "Forensic Computing Engineering",
        "Wood Industry Engineering",
        "Actuarial Sciences",
        "Astronomy and Space Sciences",
        "Horticulture",
        "Fisheries Technology Engineering",
        "Printing Technologies",
        "Nutrition and Dietetics",
        "Information Security Technology",
        "Computer Science",
        "Computer Engineering",
        "Computer Technology and Information Systems",
        "Computer and Instructional Technologies Teaching",
        "Information Systems Engineering",
        "Information Systems and Technologies",
        "Plant Protection",
        "Plant Production and Technologies",
        "Bioinformatics and Genetics",
        "Biochemistry",
        "Biology",
        "Biology Teaching",
        "Biomedical Engineering",
        "Biomechanics",
        "Biosystems Engineering",
        "Biotechnology",
        "Ore Preparation Engineering",
        "Environmental Engineering",
        "Marine Science and Technology Engineering",
        "Marine Transportation Business Engineering",
        "Leather Engineering",
        "Digital Game Design",
        "Speech and Language Therapy",
        "Dentistry (5-Year Program)",
        "Midwifery",
        "Pharmacy (5-Year Program)",
        "Electrical Engineering",
        "Electrical-Electronic Engineering",
        "Electronic Engineering",
        "Electronics and Communication Engineering",
        "Industrial Engineering",
        "Industrial Design",
        "Industrial Design Engineering",
        "Energy Engineering",
        "Energy Systems Engineering",
        "Occupational Therapy",
        "Elementary Science Teaching",
        "Physics",
        "Physics Engineering",
        "Physics Teaching",
        "Physiotherapy and Rehabilitation",
        "Photonics",
        "Ship Building and Marine Machinery Engineering",
        "Marine Machinery Operation Engineering",
        "Ship and Marine Technology Engineering",
        "Ship and Yacht Design",
        "Genetics and Biomechanics",
        "Genetics and Life Sciences Programs",
        "Geomatics Engineering",
        "Food Engineering",
        "Food Technology",
        "Surveying Engineering Base Scores",
        "Aviation Electrical and Electronics",
        "Aviation and Space Engineering",
        "Animal Production and Technologies",
        "Nursing",
        "Hydrogeology Engineering",
        "Interior Architecture",
        "Elementary Mathematics Teaching",
        "Manufacturing Engineering",
        "Civil Engineering",
        "Statistics",
        "Statistics and Computer Sciences",
        "Occupational Health and Safety",
        "Business Engineering",
        "Geophysics Engineering",
        "Geology Engineering",
        "Poultry Farming",
        "Urban Design and Landscape Architecture",
        "Chemistry",
        "Chemical Engineering",
        "Chemistry Teaching",
        "Chemistry-Biology Engineering",
        "Control and Automation Engineering",
        "Mining Engineering",
        "Mechanical Engineering",
        "Materials Science and Engineering",
        "Materials Science and Nanotechnology Engineering",
        "Materials Science and Technologies",
        "Mathematics",
        "Mathematics Engineering",
        "Mathematics Teaching",
        "Mathematics and Computer Sciences",
        "Mechatronics Engineering",
        "Metallurgy and Materials Engineering",
        "Meteorology Engineering",
        "Architecture",
        "Molecular Biology and Genetics",
        "Molecular Biotechnology",
        "Engineering Programs",
        "Engineering and Natural Sciences Programs",
        "Nanoscience and Nanotechnology",
        "Nanotechnology Engineering",
        "Nuclear Energy Engineering",
        "Audiology",
        "Optics and Acoustics Engineering",
        "Forest Industry Engineering",
        "Forestry Engineering",
        "Automotive Engineering",
        "Perfusion",
        "Petroleum and Natural Gas Engineering",
        "Landscape Architecture",
        "Piloting",
        "Rail Systems Engineering",
        "Hydraulic and Water Resources Engineering",
        "Aquaculture Engineering",
        "Dairy Technology",
        "City and Regional Planning",
        "Agricultural Machinery and Technologies Engineering",
        "Agricultural Biotechnology",
        "Agricultural Genetics Engineering",
        "Agricultural Structures and Irrigation",
        "Field Crops",
        "Textile Engineering",
        "Medicine (6-Year Program)",
        "Medical Engineering",
        "Seed Science and Technology"
    )
    val sayisalikiYilliBolumlerEN = listOf(
        "Emergency and Disaster Management",
        "Oral and Dental Health",
        "Alternative Energy Sources Technology",
        "Surgical Services",
        "Anesthesia",
        "Shoe Design and Production",
        "Concrete Technology",
        "Information Security Technology",
        "Computer-Aided Design and Animation",
        "Computer Operation",
        "Computer Programming",
        "Computer Technology",
        "Plant Protection",
        "Biochemistry",
        "Biomedical Device Technology",
        "Paint Technology",
        "Geographic Information Systems",
        "Geographic Information Systems and Technologies",
        "Environmental Protection and Control",
        "Environmental Health",
        "Marine Transportation and Operations",
        "Leather Technology",
        "Dental Prosthesis Technology",
        "Dialysis",
        "Natural Gas and Installation Technology",
        "Casting",
        "Pharmacy Services",
        "Electrical Engineering",
        "Electricity Generation, Transmission, and Distribution",
        "Electrical Appliance Technology",
        "Electromechanical Conveyors",
        "Electronic Communication Technology",
        "Electronic Technology",
        "Electroneurophysiology",
        "Industrial Product Design",
        "Industrial Glass and Ceramics",
        "Industrial Mold Making",
        "Energy Facility Management",
        "Disabled Care and Rehabilitation",
        "Home Care for Patients",
        "Physiotherapy",
        "Gas and Installation Technology",
        "Shipbuilding",
        "Marine Machinery Operation",
        "Geotechnical",
        "Food Quality Control and Analysis",
        "Food Technology",
        "Clothing Production Technology",
        "Surveying and Cadastre",
        "Air Conditioning and Refrigeration Technology",
        "First Aid and Emergency",
        "Construction Technology",
        "Internet and Network Technologies",
        "Heavy Equipment Operation",
        "Occupational Health and Safety",
        "Chemical Technology",
        "Control and Automation Technology",
        "Laboratory and Veterinary Health",
        "Laboratory Technology",
        "Tire and Plastic Technology",
        "Mining Technology",
        "Machinery",
        "Machine, Drawing, and Construction",
        "Mechatronics",
        "Mobile Technologies",
        "Furniture and Decoration",
        "Nuclear Technology and Radiation Safety",
        "Nuclear Medicine Techniques",
        "Audiometry",
        "Opticianry",
        "Orthopedic Prosthesis and Orthosis",
        "Auto Painting and Body",
        "Automotive Technology",
        "Autopsy Assistance",
        "Pathology Laboratory Techniques",
        "Perfusion Techniques",
        "Podiatry",
        "Radio and Television Technology",
        "Radiotherapy",
        "Refinery and Petrochemical Technology",
        "Rail Systems Electrical and Electronics Technology",
        "Rail Systems Machinery Technology",
        "Rail Systems Train Operation",
        "Rail Systems Track Technology",
        "Health Information Systems Technology",
        "Stage and Performing Arts Technology",
        "Ceramics, Glass, and Porcelain",
        "Agricultural Machinery",
        "Textile Technology",
        "Textile and Carpet Machinery",
        "Medical Imaging Techniques",
        "Medical Laboratory Techniques",
        "Aircraft Technology",
        "Quality Control in Production",
        "Web Design and Coding",
        "Construction Inspection",
        "Building Painting",
        "Building Installation Technology",
        "Building Insulation Technology"
    )

    val esitdortYillikBolumlerEN = listOf(
        "Family and Consumer Sciences",
        "Coach Training",
        "Anthropology",
        "Archaeology",
        "Shoe Design and Production",
        "Banking",
        "Banking and Finance",
        "Banking and Insurance",
        "Physical Education and Sports Teaching",
        "Information and Document Management",
        "History of Science",
        "Labor Economics and Industrial Relations",
        "Child Development",
        "Maritime Business Management",
        "Exercise and Sports Sciences",
        "Econometrics",
        "Economics",
        "Economics and Finance",
        "Energy Management",
        "Philosophy",
        "Philosophy Group Teaching",
        "Real Estate Development and Management",
        "Entrepreneurship",
        "Graphics",
        "Graphic Design",
        "Customs Management",
        "Aviation Management",
        "Law",
        "Interior Architecture and Environmental Design",
        "Economics and Administrative Sciences Programs",
        "Economics and Administrative Programs",
        "Economy",
        "Human Resources Management",
        "Islamic Economics and Finance",
        "Business Administration",
        "Public Administration",
        "Classical Archaeology",
        "Jewelry and Jewelry Design",
        "Preservation and Restoration of Cultural Heritage",
        "Global Politics and International Relations",
        "Logistics Management",
        "Finance",
        "Fashion Design",
        "Accounting and Auditing",
        "Accounting and Finance Management",
        "Museology",
        "Organic Farming Management",
        "Hotel Management",
        "Marketing",
        "Politics and Economics",
        "Protohistory and Ancient Near Eastern Archaeology",
        "Psychology",
        "Psychological Counseling and Guidance",
        "Psychological Counseling and Guidance Teaching",
        "Guidance and Psychological Counseling",
        "Recreation",
        "Health Management",
        "Art and Social Sciences Programs",
        "Capital Markets",
        "Travel Management",
        "Travel Management and Tourism Guiding",
        "Classroom Teaching",
        "Insurance",
        "Insurance and Actuarial Sciences",
        "Insurance and Risk Management",
        "Insurance and Social Security",
        "Political Sciences",
        "Political Science",
        "Political Science and Public Administration",
        "Political Science and International Relations",
        "Social Work",
        "Social and Political Sciences",
        "Sociology",
        "Sports Management",
        "Jewelry Design",
        "Land Registry and Cadastre",
        "Agricultural Economics",
        "Agricultural Trade and Business Management",
        "Prehistoric Archaeology",
        "Technology and Knowledge Management",
        "Textile Design",
        "Textile and Fashion Design",
        "Tourism Management",
        "Tourism and Hotel Management",
        "Turkish Islamic Archaeology",
        "International Economic Relations",
        "International Finance",
        "International Finance and Banking",
        "International Entrepreneurship",
        "International Relations",
        "International Business Management",
        "International Trade",
        "International Trade and Finance",
        "International Trade and Financing",
        "International Trade and Management",
        "International Trade and Logistics",
        "International Transportation Systems",
        "Food and Beverage Management",
        "Management Sciences Programs",
        "Management Information Systems"
    )
    val esitikiYilliBolumlerEN = listOf(
        "Banking and Insurance",
        "Printing and Publishing Technologies",
        "Information Management",
        "Tea Farming and Processing Technology",
        "Environmental Cleaning and Inspection",
        "Turf Field Establishment and Management",
        "Child Protection and Care Services",
        "Marine Brokerage",
        "Marine and Port Management",
        "Foreign Trade",
        "Natural Building Stones Technology",
        "Real Estate and Property Management",
        "Industrial Poultry Farming",
        "Heritage Conservation",
        "Meat and Products Technology",
        "Hazelnut Expertise",
        "Sapling Cultivation",
        "Graphic Design",
        "Aviation Logistics",
        "Interior Design",
        "Catering Services",
        "Human Resources Management",
        "Business Management",
        "Cooperatives",
        "Jewelry and Jewelry Design",
        "Cultural Fishing",
        "Logistics",
        "Finance",
        "Marina Management",
        "Marina and Yacht Management",
        "Securities and Capital Markets",
        "Fruit and Vegetable Processing Technology",
        "Architectural Restoration",
        "Fashion Management",
        "Fashion Design",
        "Accounting and Tax Practices",
        "Organic Farming",
        "Forestry and Forest Products",
        "Bus Captaincy",
        "Private Security and Protection",
        "Marketing",
        "Retail Sales and Store Management",
        "Landscape and Ornamental Plants",
        "Postal Services",
        "Rail Systems Management",
        "Health Institutions Management",
        "Health Tourism Management",
        "Stage and Set Design",
        "Greenhouse Farming",
        "Civil Air Transportation Management",
        "Civil Aviation Cabin Services",
        "Civil Defense and Firefighting",
        "Social Security",
        "Social Services",
        "Sports Management",
        "Underwater Technology",
        "Ornamental Plant Cultivation",
        "Dairy and Dairy Products Technology",
        "Land Registry and Cadastre",
        "Agriculture",
        "Agricultural Business Management",
        "Agricultural Products Preservation and Storage Technology",
        "Field Crops",
        "Medical Promotion and Marketing",
        "Medical and Aromatic Plants",
        "Seed Production",
        "Tourism and Hotel Management",
        "Tourism and Travel Services",
        "Flight Operations Management",
        "Transportation and Traffic Services",
        "Yacht Management and Operations",
        "Olive and Olive Processing Technology"
    )

}
